=== moonym/kuali-rice/JEE/StudentWork-Solutions - XML/XMLIntro/workspace/Lab04.2/order.xsd
<?xml version='1.0'?>

<!--
 * This code is sample code, provided as-is, and we make no
 * warranties as to its correctness or suitablity for
 * any purpose.
 *
 * We hope that it's useful to you.  Enjoy.
 * Copyright 2004-10 LearningPatterns Inc.
-->

<!-- schema for JavaTunes order -->

<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

  <xsd:element name='order' type='orderType'/>

  <xsd:complexType name='orderType'>
    <xsd:sequence>
      <xsd:element name='customer' type='customerType'/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name='customerType'>
    <xsd:sequence>
      <xsd:element name='name'    type='xsd:string'/>
      <xsd:element name='street'  type='xsd:string'/>
      <xsd:element name='apt'     type='xsd:string'/>
      <xsd:element name='city'    type='xsd:string'/>
      <xsd:choice>
        <xsd:sequence>
          <xsd:element name='state'   type='xsd:string'/>
          <xsd:element name='zipcode' type='xsd:string'/>
        </xsd:sequence>
        <xsd:sequence>
          <xsd:element name='prov'  type='xsd:string'/>
          <xsd:element name='pcode' type='xsd:string'/>
        </xsd:sequence>
      </xsd:choice>
      <xsd:element name='shipper'>      <!-- uses an anonymous type -->
        <xsd:complexType>
          <!-- no content model because shipper is an empty element (<shipper/>) -->
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== moonym/kuali-rice/JEE/StudentWork-Solutions - XML/XMLIntro/workspace/Lab04.2/simpleorder.xml
<?xml version='1.0'?>

<!--
 * This code is sample code, provided as-is, and we make no
 * warranties as to its correctness or suitablity for
 * any purpose.
 *
 * We hope that it's useful to you.  Enjoy.
 * Copyright 2004-10 LearningPatterns Inc.
-->

<!-- JavaTunes order XML document (simplified) -->

<order xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
       xsi:noNamespaceSchemaLocation='order.xsd'>
  <customer>
    <name>Susan Phillips</name>
    <street>763 Rodeo Circle</street>
    <apt>1A</apt>
    <city>San Francisco</city>
    <state>CA</state>
    <zipcode>94109</zipcode>
    <shipper/>
  </customer>
</order>
