=== moonym/kuali-rice/JEE/StudentWork-Solutions - XML/XMLIntro/workspace/Lab04.5_optional/orderns.xsd
<?xml version='1.0'?>

<!--
 * This code is sample code, provided as-is, and we make no
 * warranties as to its correctness or suitablity for
 * any purpose.
 *
 * We hope that it's useful to you.  Enjoy.
 * Copyright 2004-10 LearningPatterns Inc.
-->

<!-- schema for JavaTunes order with namespace support and some useful derived types -->

<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
            xmlns='http://www.javatunes.com/order'
            targetNamespace='http://www.javatunes.com/order'
            elementFormDefault='qualified'>

  <xsd:element name='order' type='orderType'/>

  <xsd:complexType name='orderType'>
    <xsd:sequence>
      <xsd:element name='customer' type='customerType'/>
      <xsd:element name='item'     type='itemType' maxOccurs='unbounded'/>
    </xsd:sequence>
    <xsd:attribute name='ID'       type='xsd:ID'       use='required'/>
    <xsd:attribute name='dateTime' type='xsd:dateTime' use='required'/>
  </xsd:complexType>

  <xsd:complexType name='customerType'>
    <xsd:sequence>
      <xsd:element name='name'>         <!-- uses an anonymous type -->
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name='firstName' type='xsd:string'/>
            <xsd:element name='lastName'  type='xsd:string'/>
          </xsd:sequence>
          <xsd:attribute name='title'     type='xsd:string'/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name='street'  type='xsd:string'/>
      <xsd:element name='apt'     type='xsd:string' minOccurs='0'/>
      <xsd:element name='city'    type='xsd:string'/>
      <xsd:choice>
        <xsd:sequence>
          <xsd:element name='state'   type='USstatesType'/>
          <xsd:element name='zipcode' type='zipcodeType'/>
        </xsd:sequence>
        <xsd:sequence>
          <xsd:element name='prov'  type='xsd:string'/>
          <xsd:element name='pcode' type='xsd:string'/>
        </xsd:sequence>
      </xsd:choice>
      <xsd:element name='shipper'>      <!-- uses an anonymous type -->
        <xsd:complexType>
          <!-- no content model because shipper is an empty element (<shipper/>) -->
          <xsd:attribute name='name'       type='shipperNameType' default='USMail'/>
          <xsd:attribute name='accountNum' type='xsd:string'      use='optional'/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name='itemType'>
    <xsd:sequence>
      <xsd:element name='name'        type='xsd:string'/>
      <xsd:element name='artist'      type='xsd:string' maxOccurs='unbounded'/>
      <xsd:element name='releaseDate' type='xsd:date'/>
      <xsd:element name='listPrice'   type='xsd:decimal'/>
      <xsd:element name='price'       type='xsd:decimal' default='9.99'/>
    </xsd:sequence>
    <xsd:attribute name='ID'   type='xsd:ID'      use='required'/>
    <xsd:attribute name='type' type='xsd:NMTOKEN' default='CD'/>
  </xsd:complexType>

  <xsd:simpleType name='shipperNameType'>
    <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='USMail'/>
      <xsd:enumeration value='FedEx'/>
      <xsd:enumeration value='UPS'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name='zipcodeType'>
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='[0-9]{5}(-[0-9]{4})?'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name='USstatesType'>
    <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='NY'/>
      <xsd:enumeration value='CA'/>
      <xsd:enumeration value='WY'/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== moonym/kuali-rice/JEE/StudentWork-Solutions - XML/XMLIntro/workspace/Lab04.5_optional/orderns.xml
<?xml version='1.0'?>

<!--
 * This code is sample code, provided as-is, and we make no
 * warranties as to its correctness or suitablity for
 * any purpose.
 *
 * We hope that it's useful to you.  Enjoy.
 * Copyright 2004-10 LearningPatterns Inc.
-->

<!-- JavaTunes order XML document with namespace support -->

<order xmlns='http://www.javatunes.com/order'
       xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
       xsi:schemaLocation='http://www.javatunes.com/order orderns.xsd'
       ID='_03230413' dateTime='2002-03-24T01:20:00'>
  <customer>
    <name title='Ms.'>
      <firstName>Rachel</firstName>
      <lastName>Jacobs</lastName>
    </name>
    <street>1408 Fell St.</street>
    <city>Oneida</city>
    <state>NY</state>                                 <!-- must be NY | CA | WY -->
    <zipcode>14180-1234</zipcode>                     <!-- zip-plus4 is also supported -->
    <shipper name='FedEx' accountNum='77-63-2478'/>   <!-- must be USMail | FedEx | UPS -->
  </customer>
  <item ID='CD514'>
    <name>So</name>
    <artist>Peter Gabriel</artist>
    <releaseDate>1986-10-03</releaseDate>
    <listPrice>17.97</listPrice>
    <price>13.99</price>
  </item>
  <item ID='CD506'>
    <name>Seal</name>
    <artist>Seal</artist>
    <releaseDate>1991-08-18</releaseDate>
    <listPrice>17.97</listPrice>
    <price>14.99</price>
  </item>
</order>
