=== moonym/kuali-rice/JEE/StudentWork-Solutions - XML/XMLIntro/workspace/Lab04.3/order.xsd
<?xml version='1.0'?>

<!--
 * This code is sample code, provided as-is, and we make no
 * warranties as to its correctness or suitablity for
 * any purpose.
 *
 * We hope that it's useful to you.  Enjoy.
 * Copyright 2004-10 LearningPatterns Inc.
-->

<!-- schema for JavaTunes order -->

<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

  <xsd:element name='order' type='orderType'/>

  <xsd:complexType name='orderType'>
    <xsd:sequence>
      <xsd:element name='customer' type='customerType'/>
      <xsd:element name='item'     type='itemType' maxOccurs='unbounded'/>
    </xsd:sequence>
    <xsd:attribute name='ID'       type='xsd:ID'       use='required'/>
    <xsd:attribute name='dateTime' type='xsd:dateTime' use='required'/>
  </xsd:complexType>

  <xsd:complexType name='customerType'>
    <xsd:sequence>
      <xsd:element name='name'    type='xsd:string'/>
      <xsd:element name='street'  type='xsd:string'/>
      <xsd:element name='apt'     type='xsd:string' minOccurs='0'/>
      <xsd:element name='city'    type='xsd:string'/>
      <xsd:choice>
        <xsd:sequence>
          <xsd:element name='state'   type='xsd:string'/>
          <xsd:element name='zipcode' type='xsd:string'/>
        </xsd:sequence>
        <xsd:sequence>
          <xsd:element name='prov'  type='xsd:string'/>
          <xsd:element name='pcode' type='xsd:string'/>
        </xsd:sequence>
      </xsd:choice>
      <xsd:element name='shipper'>      <!-- uses an anonymous type -->
        <xsd:complexType>
          <!-- no content model because shipper is an empty element (<shipper/>) -->
          <xsd:attribute name='name'       type='xsd:NMTOKEN' default='USMail'/>
          <xsd:attribute name='accountNum' type='xsd:string'  use='optional'/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name='itemType'>
    <xsd:sequence>
      <xsd:element name='name'        type='xsd:string'/>
      <xsd:element name='artist'      type='xsd:string' maxOccurs='unbounded'/>
      <xsd:element name='releaseDate' type='xsd:date'/>
      <xsd:element name='listPrice'   type='xsd:decimal'/>
      <xsd:element name='price'       type='xsd:decimal' default='9.99'/>
    </xsd:sequence>
    <xsd:attribute name='ID'   type='xsd:ID'      use='required'/>
    <xsd:attribute name='type' type='xsd:NMTOKEN' default='CD'/>
  </xsd:complexType>

</xsd:schema>

=== moonym/kuali-rice/JEE/StudentWork-Solutions - XML/XMLIntro/workspace/Lab04.3/order.xml
<?xml version='1.0'?>

<!--
 * This code is sample code, provided as-is, and we make no
 * warranties as to its correctness or suitablity for
 * any purpose.
 *
 * We hope that it's useful to you.  Enjoy.
 * Copyright 2004-10 LearningPatterns Inc.
-->

<!--
Comment out this PI to see the full document in a browser.
If the PI is left in, you should see the customer info in a table.
-->
<!-- ?xml-stylesheet type='text/xsl' href='file:///StudentWork/XML/customer.xsl'? -->

<!-- JavaTunes order XML document -->

<order xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
       xsi:noNamespaceSchemaLocation='order.xsd'
       ID='_12050826' dateTime='2002-02-07T16:20:00'>
  <customer>
    <name>James Heft</name>
    <street>455 Meadow St.</street>
    <city>Lodi</city>
    <state>CA</state>
    <zipcode>95112</zipcode>
    <shipper name='UPS' accountNum='544-8775-1'/>
    <?pager UPS 544-8775-1?>
  </customer>
  <item ID='CD513'>
    <name>My, I'm Large</name>
    <artist>Bobs</artist>
    <releaseDate>1987-02-20</releaseDate>
    <listPrice>11.97</listPrice>
    <price>11.97</price>
  </item>
  <item ID='CD518'>
    <name>Escape</name>
    <artist>Journey</artist>
    <artist>Seals &amp; Crofts</artist>
    <releaseDate>1981-02-25</releaseDate>
    <listPrice>11.97</listPrice>
    <price/>  <!-- take the default value -->
  </item>
</order>
